/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ReporteDAO;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JComponent;
import javax.swing.table.DefaultTableModel;
import model.Validador;
import sound.SoundManager;

public class Reporte extends javax.swing.JFrame {

    /**
     * Creates new form Reporte
     */
    public Reporte() {
        initComponents();
        setLocationRelativeTo(null);
        jButtonLimpiar.setEnabled(false);
        actualizarEstadoFiltros();
    }

    public static void limpiarTabla(DefaultTableModel modelo) {
        modelo.setRowCount(0);
    }

    public void limpiarFiltros() {
        // Limpiar los campos de texto
        jFormattedTextFieldDesde.setText("");
        jFormattedTextFieldHasta.setText("");
        jFormattedTextFieldFolio.setText("");
        jSpinnerDesdeMonto.setValue(0);
        jFormattedTextFieldRutCliente.setText("");
        jFormattedTextFieldRutCajero.setText("");

        // no se si es necesario esto porque igual esta de mas
        //    jComboBoxMetodoPago.setSelectedIndex(0); 
        //    jComboBoxFiltrarPor.setSelectedIndex(0);  
    }

    public void actualizarEstadoFiltros() {
        // Deshabilitar todos los campos por defecto
        Map<JComponent, Boolean> fields = new HashMap<>();
        fields.put(jFormattedTextFieldDesde, false);
        fields.put(jFormattedTextFieldHasta, false);
        fields.put(jFormattedTextFieldFolio, false);
        fields.put(jSpinnerDesdeMonto, false);
        fields.put(jFormattedTextFieldRutCliente, false);
        fields.put(jFormattedTextFieldRutCajero, false);
        fields.put(jComboBoxMetodoPago, false);

        // Obtener el índice de la selección en el combo box
        int index = jComboBoxFiltrarPor.getSelectedIndex();

        // Establecer el estado de los campos según el índice seleccionado
        switch (index) {
            case 0:
                fields.put(jFormattedTextFieldDesde, true);
                fields.put(jFormattedTextFieldHasta, true);
                break;
            case 1:
                fields.put(jFormattedTextFieldFolio, true);
                break;
            case 2:
                fields.put(jSpinnerDesdeMonto, true);
                break;
            case 3:
                fields.put(jFormattedTextFieldRutCliente, true);
                break;
            case 4:
                fields.put(jFormattedTextFieldRutCajero, true);
                break;
            case 5:
                fields.put(jComboBoxMetodoPago, true);
                break;
        }

        // Actualizar los componentes en función de los valores del mapa
        for (Map.Entry<JComponent, Boolean> entry : fields.entrySet()) {
            entry.getKey().setEnabled(entry.getValue());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jFormattedTextFieldDesde = new javax.swing.JFormattedTextField();
        jLabelDesde = new javax.swing.JLabel();
        jFormattedTextFieldHasta = new javax.swing.JFormattedTextField();
        jLabelHasta = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jFormattedTextFieldFolio = new javax.swing.JFormattedTextField();
        jLabelFolio = new javax.swing.JLabel();
        jButtonLimpiar = new javax.swing.JButton();
        jComboBoxFiltrarPor = new javax.swing.JComboBox<>();
        jLabelFiltrarPor = new javax.swing.JLabel();
        jLabelDesdeMonto = new javax.swing.JLabel();
        jFormattedTextFieldRutCliente = new javax.swing.JFormattedTextField();
        jLabelRutCliente = new javax.swing.JLabel();
        jFormattedTextFieldRutCajero = new javax.swing.JFormattedTextField();
        jLabelRutCajero = new javax.swing.JLabel();
        jComboBoxMetodoPago = new javax.swing.JComboBox<>();
        jLabelMetodoPago = new javax.swing.JLabel();
        jLabelHastaMonto = new javax.swing.JLabel();
        jSpinnerDesdeMonto = new javax.swing.JSpinner();
        jSpinnerHastaMonto = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSalida = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reportes");

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo-mini.png"))); // NOI18N

        try {
            jFormattedTextFieldDesde.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDesdeActionPerformed(evt);
            }
        });

        jLabelDesde.setText("Desde (año/mes/dia)");

        try {
            jFormattedTextFieldHasta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldHastaActionPerformed(evt);
            }
        });

        jLabelHasta.setText("Hasta (año/mes/dia)");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jFormattedTextFieldFolio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldFolioActionPerformed(evt);
            }
        });
        jFormattedTextFieldFolio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldFolioKeyTyped(evt);
            }
        });

        jLabelFolio.setText("Folio");

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jComboBoxFiltrarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rango de fecha", "Folio", "Monto", "RUT Cliente", "RUT Cajero", "Metodo de Pago" }));
        jComboBoxFiltrarPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltrarPorActionPerformed(evt);
            }
        });

        jLabelFiltrarPor.setText("Filtrar por");

        jLabelDesdeMonto.setText("Desde el monto");

        try {
            jFormattedTextFieldRutCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelRutCliente.setText("RUT Cliente");

        try {
            jFormattedTextFieldRutCajero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelRutCajero.setText("RUT Cajero");

        jComboBoxMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debito", "Credito", "Efectivo", "Edenred" }));

        jLabelMetodoPago.setText("Metodo de pago");

        jLabelHastaMonto.setText("Hasta el monto");

        jSpinnerDesdeMonto.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinnerHastaMonto.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSpinnerDesdeMonto)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelDesde, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldDesde, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jLabelFolio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldRutCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldFolio, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jLabelRutCliente, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(jLabelDesdeMonto)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelHasta)
                                .addComponent(jFormattedTextFieldHasta, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(jLabelRutCajero)
                                .addComponent(jFormattedTextFieldRutCajero)
                                .addComponent(jComboBoxMetodoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelMetodoPago))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxFiltrarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFiltrarPor))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHastaMonto)
                            .addComponent(jSpinnerHastaMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDesde)
                    .addComponent(jLabelHasta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFolio)
                            .addComponent(jLabelMetodoPago))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelRutCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelRutCajero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldRutCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelFiltrarPor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFiltrarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHastaMonto)
                    .addComponent(jLabelDesdeMonto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerDesdeMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerHastaMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTableSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Folio", "RUT cliente", "RUT cajero", "Fecha", "Metodo de pago", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSalida.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableSalida);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
            .addComponent(jSeparator1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        Hub hubWindow = new Hub();
        hubWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jFormattedTextFieldDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDesdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDesdeActionPerformed

    private void jFormattedTextFieldHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldHastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldHastaActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // Limpiar cualquier dato anterior en la tabla
        DefaultTableModel modelo = (DefaultTableModel) jTableSalida.getModel();
        modelo.setRowCount(0);  // Limpiamos la tabla antes de agregar los nuevos datos

        // Dependiendo de la selección, obtener los resultados
        List<String[]> ventas = new ArrayList<>();

        switch (jComboBoxFiltrarPor.getSelectedIndex()) {
            case 0: // Buscar por rango de fechas
                String fechaDesde = jFormattedTextFieldDesde.getText();  // Fecha desde
                String fechaHasta = jFormattedTextFieldHasta.getText();  // Fecha hasta
                ventas = ReporteDAO.obtenerFilasVentaPorRangoFechas(fechaDesde, fechaHasta);
                break;
            case 1: // Buscar por id_venta
                int folio = Integer.parseInt(jFormattedTextFieldFolio.getText());
                ventas = ReporteDAO.getFilasVentaPorIdVenta(folio);
                break;

            case 2: // Buscar por monto
                String monto = (String) jSpinnerDesdeMonto.getValue();
                ventas = ReporteDAO.getFilasVentaPorMonto(monto);
                break;

            case 3: // Buscar por rut_cliente
                String rutCliente = jFormattedTextFieldRutCliente.getText();
                ventas = ReporteDAO.getFilasVentaPorRutCliente(rutCliente);
                break;
            case 4:
                String rutVendedor = jFormattedTextFieldRutCajero.getText();
                ventas = ReporteDAO.getFilasVentaPorRutVendedor(rutVendedor);
                break;
            case 5:
                String metodoPago = jComboBoxMetodoPago.getSelectedItem().toString();
                ventas = ReporteDAO.getFilasVentaPorMetodoPago(metodoPago);
                break;
        }

        // Si se encontraron ventas, agregarlas a la tabla
        for (String[] venta : ventas) {
            String folio = venta[0];
            String rut_cliente = venta[1];
            String rut_vendedor = venta[2];
            String fecha = venta[3];
            String metodo_pago = venta[4];
            String monto = venta[5];

            // Agregar la fila al modelo de la tabla
            modelo.addRow(new Object[]{folio, rut_cliente, rut_vendedor, fecha, metodo_pago, monto});
        }

        // Limpiar filtros después de la búsqueda
        limpiarFiltros();
        jButtonLimpiar.setEnabled(true);

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        DefaultTableModel modelo = (DefaultTableModel) jTableSalida.getModel();
        limpiarTabla(modelo);
        SoundManager.reproducirSonido("clean");
        limpiarFiltros();
        jButtonLimpiar.setEnabled(false);


    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jComboBoxFiltrarPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltrarPorActionPerformed
        actualizarEstadoFiltros();


    }//GEN-LAST:event_jComboBoxFiltrarPorActionPerformed

    private void jFormattedTextFieldFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldFolioActionPerformed


    }//GEN-LAST:event_jFormattedTextFieldFolioActionPerformed

    private void jFormattedTextFieldFolioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldFolioKeyTyped
        Validador.bloquearSimbolos(evt);
        Validador.bloquearLetras(evt);
    }//GEN-LAST:event_jFormattedTextFieldFolioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxFiltrarPor;
    private javax.swing.JComboBox<String> jComboBoxMetodoPago;
    private javax.swing.JFormattedTextField jFormattedTextFieldDesde;
    private javax.swing.JFormattedTextField jFormattedTextFieldFolio;
    private javax.swing.JFormattedTextField jFormattedTextFieldHasta;
    private javax.swing.JFormattedTextField jFormattedTextFieldRutCajero;
    private javax.swing.JFormattedTextField jFormattedTextFieldRutCliente;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDesde;
    private javax.swing.JLabel jLabelDesdeMonto;
    private javax.swing.JLabel jLabelFiltrarPor;
    private javax.swing.JLabel jLabelFolio;
    private javax.swing.JLabel jLabelHasta;
    private javax.swing.JLabel jLabelHastaMonto;
    private javax.swing.JLabel jLabelMetodoPago;
    private javax.swing.JLabel jLabelRutCajero;
    private javax.swing.JLabel jLabelRutCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerDesdeMonto;
    private javax.swing.JSpinner jSpinnerHastaMonto;
    private javax.swing.JTable jTableSalida;
    // End of variables declaration//GEN-END:variables
}
